title: Selina WP4
nav:
  - name: Home
    link: /
  - name: Infos
    children:
      - name: test
        link: /informative-survey
      - name: test 2
        link: /informative-survey#test
  - name: Survey
    link: /survey
  - name: Last submission
    link: /survey-debug
