title: Selina WP4
nav:
  - name: Home
    link: /
  - name: About
    children:
      - name: Is this website for you?
        link: /about-website
      - name: What is the goal of this website?
        link: /about-website-goal
      - name: What is EU SELINA project?
        link: /about-selina
  - name: Learn more about
    link: /
    children:
      - name: Our writing guidance
        link: /intro-writing-guidance
      - name: Commissionning with our guidance
        link: /intro-commissionning
      - name: Concepts behind ecosystem service assessments
        link: /intro-es-concepts
  - name: Create your Terms of Reference
    children:
      - name: Read me first
        link: /writing-tor
      - name: Survey
        link: /survey
      - name: Survey FAQ
        link: /informative-survey
  - name: Examples
    link: /examples-tor
  - name: Caveats and limitations
    link: /caveats-limitations

home:
  title: Understand what you need, to get what you want 
  subtitle: Welcome to your discovery of ecosystem service assessment, a clear guide to write a tender tailored to your needs. 
  cta_text: Start creating your Terms fo Reference now!
  cta_url: /survey

footer:
  text: SELINA receives funding from the European Union's Horizon Europe research and innovation programme under grant agreement No 101060415. Views and opinions expressed are however those of the author(s) only and do not necessarily reflect those of the European Union or the European Commission. Neither the EU nor the EC can be held responsible for them.
